# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 731, 681))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: #282828;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = PlotWidget(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(20, 290, 661, 341))
        self.graphicsView.setStyleSheet("")
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 260, 111, 21))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 130, 161, 30))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(290, 170, 101, 21))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(400, 170, 110, 30))
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 130, 181, 30))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(190, 30, 181, 41))
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 0, 181, 41))
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(370, 10, 181, 21))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-radius: 10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 40, 211, 21))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border-radius: 10px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 190, 121, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 91, 21))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 230, 21, 21))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.racer_1 = QtWidgets.QLineEdit(self.frame)
        self.racer_1.setGeometry(QtCore.QRect(410, 70, 141, 21))
        self.racer_1.setStyleSheet("QLineEdit{\n"
"border-radius: 10px;\n"
"}")
        self.racer_1.setObjectName("racer_1")
        self.racer_2 = QtWidgets.QLineEdit(self.frame)
        self.racer_2.setGeometry(QtCore.QRect(410, 100, 141, 21))
        self.racer_2.setStyleSheet("QLineEdit{\n"
"border-radius: 10px;\n"
"}")
        self.racer_2.setObjectName("racer_2")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(190, 70, 201, 41))
        self.label_6.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(560, 230, 101, 21))
        self.label_7.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(560, 250, 101, 21))
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(560, 270, 101, 20))
        self.label_9.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Получить показания"))
        self.pushButton_5.setText(_translate("MainWindow", "Выйти из соревнования"))
        self.label_2.setText(_translate("MainWindow", "Дата проведения"))
        self.pushButton_4.setText(_translate("MainWindow", "Зарегистрировать соревнование"))
        self.label_5.setText(_translate("MainWindow", "Введите имя организатора:"))
        self.label.setText(_translate("MainWindow", "Введите название соревнования:"))
        self.pushButton.setText(_translate("MainWindow", "Выбор гонки"))
        self.pushButton_2.setText(_translate("MainWindow", "Начать гонку"))
        self.label_3.setText(_translate("MainWindow", "30"))
        self.label_6.setText(_translate("MainWindow", "Введите номера измеряемых гонщиков:"))
        self.label_7.setText(_translate("MainWindow", "Гонка:"))
from pyqtgraph import PlotWidget
