# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 10, 121, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 20, 141, 21))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-radius: 10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 101, 21))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 60, 91, 21))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 60, 21, 21))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 130, 110, 30))
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 181, 41))
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 60, 170, 21))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border-radius: 10px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 90, 181, 30))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -29, 521, 621))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: #282828;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = PlotWidget(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(30, 220, 451, 341))
        self.graphicsView.setStyleSheet("")
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 180, 141, 31))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 120, 161, 30))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Выбор гонки"))
        self.label.setText(_translate("MainWindow", "Введите название соревнования:"))
        self.label_2.setText(_translate("MainWindow", "Дата проведения"))
        self.pushButton_2.setText(_translate("MainWindow", "Начать гонку"))
        self.label_3.setText(_translate("MainWindow", "60"))
        self.label_5.setText(_translate("MainWindow", "Введите имя организатора:"))
        self.pushButton_4.setText(_translate("MainWindow", "Зарегистрировать соревнование"))
        self.pushButton_3.setText(_translate("MainWindow", "Получить показания"))
        self.pushButton_5.setText(_translate("MainWindow", "Выйти из соревнования"))
from pyqtgraph import PlotWidget
